### ISSUE TITLE
_.pluck fixed but now getting a Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Darrencwood** [anzai/grafana-graph3d-panel#1]
Hi,

I'm new to coding so please forgive me any stupid questions , I tried this plugin and originially got a error at _.pluck so changed that to match the new _,map but I'm now getting ;

TypeError: Cannot read property '0' of undefined
    at addGraph3d (http://someserver:3000/public/plugins/grafana-graph3d-panel/rendering.js?bust=1481533003526:148:27)
    at render (http://someserver:3000/public/plugins/grafana-graph3d-panel/rendering.js?bust=1481533003526:45:9)
    at eval (http://someserver:3000/public/plugins/grafana-graph3d-panel/rendering.js?bust=1481533003526:13:7)
    at e.emit (http://someserver:3000/public/app/boot.85c49108.js:48:17959)
    at a.emit (http://someserver:3000/public/app/boot.85c49108.js:48:19617)
    at Graph3dCtrl.a.render (http://someserver:3000/public/app/boot.85c49108.js:42:9821)
    at Graph3dCtrl.onDataReceived (http://someserver:3000/public/plugins/grafana-graph3d-panel/graph3d_ctrl.js?bust=1481533003526:143:18)
    at e.emit (http://someserver:3000/public/app/boot.85c49108.js:48:17526)
    at a.emit (http://someserver:3000/public/app/boot.85c49108.js:48:19617)
    at Graph3dCtrl.f.handleQueryResult (http://someserver:3000/public/app/boot.85c49108.js:42:19805)

Any ideas, I'm keen to help to get this plugin going.

**Comment by Darrencwood** [comment]
Is this related?
http://stackoverflow.com/questions/29431225/javascript-uncaught-typeerror-cannot-read-property-0-of-undefined

**Comment by anzai** [comment]
@Darrencwood Thank you for trying this plugin. I'm sorry I 'm developping this plugin just for my study and haven't released as a product yet. So It may still contain some bugs...
Could you show me the original error messages with the codes before your modifying?
